import assert from 'node:assert/strict';
import {safeSongUrl,decodeEntities,extractStore,noResults,searchSongs,loadSong} from '../lib/catalog.js';
const valid='https://tabs.ultimate-guitar.com/tab/example/original-chords-12345';
const html=data=>'<div class="js-store" data-content="'+JSON.stringify({store:{page:{data}}}).replaceAll('&','&amp;').replaceAll('"','&quot;')+'"></div>';
const reply=(text,status=200)=>async()=>new Response(text,{status});
assert(safeSongUrl(valid));for(const url of ['http://tabs.ultimate-guitar.com/tab/test','https://evil.test/tab/test','https://tabs.ultimate-guitar.com@evil.test/tab/test','https://tabs.ultimate-guitar.com:4430/tab/test','https://tabs.ultimate-guitar.com/tab/test?x=1','https://tabs.ultimate-guitar.com/search.php'])assert(!safeSongUrl(url));
assert.equal(decodeEntities('&amp;quot; &quot; &#39; &#xE9;'),'&quot; " \' é');
assert.equal(extractStore(html({value:'A & B "original"'})).value,'A & B "original"');
assert(noResults('<title>No results @ Ultimate-Guitar.Com Search</title>'));assert(!noResults('<title>Page not found</title>'));
const songs=await searchSongs('Original',reply(html({results:[{type:'Chords',id:12345,song_name:'Original',artist_name:'Example',tab_url:valid,version:2},{type:'Official',tab_url:valid},{type:'Tabs',tab_url:valid},{type:'Chords',tab_url:'https://evil.test/tab/test'}]})));
assert.equal(songs.length,1);assert.equal(songs[0].version,2);
assert.deepEqual(await searchSongs('no match',reply('<title>No results @ Ultimate-Guitar.Com Search</title>',404)),[]);
await assert.rejects(searchSongs('missing',reply('<title>Not found</title>',404)));await assert.rejects(searchSongs('x',reply('Forbidden',403)));await assert.rejects(searchSongs('',reply('')));
const content='G 320033\n[Verse]\n[ch]G[/ch]     [ch]D[/ch]\nOriginal test text';
const sheet=await loadSong(valid,reply(html({tab_view:{wiki_tab:{content,username:'Author'},meta:{tuning:{value:'E A D G B E'},capo:2}}})));
assert.equal(sheet.text,content);assert.equal(sheet.author,'Author');assert.equal(sheet.tuning,'standard');assert.equal(sheet.capo,2);
assert.equal((await loadSong(valid,reply(html({tab_view:{wiki_tab:{content},meta:{tuning:{value:'D A D G B E'}}}})))).tuning,'other');
await assert.rejects(loadSong(valid,reply('missing',404)));await assert.rejects(loadSong('https://evil.test/',reply('')));await assert.rejects(loadSong(valid,reply(html({tab_view:{}}))));
await assert.rejects(searchSongs('x',reply('x'.repeat(3_000_001))));
console.log('Catalog: public chord filtering, exact text, attribution, tuning, errors, body limits and URL restrictions passed.');
